### ISSUE TITLE
Allow booting without sep

### ISSUE THREAD

**Issue by Grandboy46** [MatthewPierson/Ramiel#10]
Hey all,

There was a tool called seposfun which would allow booting to the second os by disabling sep and its functions which would allow booting to firmwares that have incompatible sep. Can you please allow users to do tethered boot or downgrade with sep being disabled. This would break apple pay, touch id and passcode which I don't mind.

**Comment by MatthewPierson** [comment]
That project was never finished, it only allowed for the booting of older Switchboard firmwares, not official iOS builds. If it ever gets updated then I'd happily include it but until then it's not really useful to Ramiel
