### ISSUE TITLE
unzipping ipsw loop catalina

### ISSUE THREAD

**Issue by cupecups** [MatthewPierson/Ramiel#12]
https://user-images.githubusercontent.com/25073725/111254969-c07b3780-8648-11eb-9dd6-4c80073777a3.mov

looping boot device menu with unzipping ipsw

**Comment by MatthewPierson** [comment]
Can you run Ramiel from the terminal, enable debug mode in settings, then try again and send me the full log?

**Comment by cupecups** [comment]
![image](https://user-images.githubusercontent.com/25073725/111256171-0df8a400-864b-11eb-900c-78432b74474d.png)

**Comment by MatthewPierson** [comment]
Can you re-download the IPSW and try again? Last time I had this issue it was due to a corrupted IPSW

**Comment by developerss** [comment]
hello @mathew and @cupecups i have tested it over catoline 10.15.1 , 2 ,3 4,5 ,6 ,7 
its works without any problem ,i think @cupecup need to learn first about it

**Comment by cupecups** [comment]
> Can you re-download the IPSW and try again? Last time I had this issue it was due to a corrupted IPSW

Sure will try download again?

**Comment by cupecups** [comment]
> hello @Mathew and @cupecups i have tested it over cataline 10.15.1 , 2 ,3 4,5 ,6 ,7 ,
> so i can confirm its works without any problem ,i think @cupecup need to learn first about it

What do you mean learn?

**Comment by developerss** [comment]
@cupecups 

obviously you need to learn lot of thing .
because where are you trying you are not saying at all , cataline working 100 percent why not working in your cataline >? obiously you are trying on vmmachin or something else similar
