### ISSUE TITLE
[Bug] cannot set convert

### ISSUE THREAD

**Issue by Guines10** [MatthewPierson/Ramiel#21]
Selected Dualbooted - 8
Selected AMFI
Selected AMSD

**Desktop (please complete the following information):**
 - macOS Version: 10.15.7
 - Machine Model: MacBook Pro 2014

**iOS/iPadOS Device(please complete the following information):**
 - Model: iPhone 8,1 iOS 14.4.1
 - iOS Version Being Booted: iOS 13.5
 - Dualbooted: Y

**Additional context**
[+] Changed CSEL to MOV
[+] Found branch pointing to 0x870010254 at 0x10184
[+] Changed ADR X21, 0x870047400 to ADR X21, 0x870048a95
[+] Enabling kernel debug...
[+] Found debug-enabled string at 0x4854e
[+] Found debug-enabled xref at 0xeaf8
[+] Found second bl after debug-enabled xref at 0xeb0c
[+] Wrote MOVZ X0, #1 to 0x87000eb0c
[+] Enabled kernel debug
[+] Unlocking nvram...
[+] Found debug-uarts string at 0x8700475f6
[+] Found debug-uarts reference at 0x49ba0
[+] setenv whitelist begins at 0x49b90
[+] Found ref to setenv whitelist at 0x2abc
[+] Forcing sub_870002aa0 to return immediately
[+] Found env whitelist at 0x49bb8
[+] Found ref to env whitelist at 0x2b08
[+] Forcing sub_870002af0 to return immediately
[+] Found "com.apple.System." string at 0x870049767
[+] Found reference to "com.apple.System." at 0x2f3d4
[+] Forcing sub_87002f3cc to return immediately
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x48409
[+] Found IMG4 xref at 0xc928
[+] Found beginning of _image4_get_partial at 0xc8b8
[+] Found xref to _image4_get_partial at 0xd31c
[+] Found start of sub_87000d23c
[+] Found ADR X2, 0x870049ef0 at 0xd840
[+] Call to 0xcbcc
[+] RET found for sub_87000cbcc at 0xd198
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to /Applications/Ramiel.app/Contents/Resources/RamielFiles/ibec.pwn
[e] cannot set convert

**Comment by MatthewPierson** [comment]
That's not a bug, that's expected on some devices. It doesn't have any negative effect if it shows up at all.
