### ISSUE TITLE
iPhone 5S 12.5.2 Divise

### ISSUE THREAD

**Issue by Visualwit** [MatthewPierson/Ramiel#26]
I Am Trying To Use Divise To DualBoot My iPhone 5S Running iOS 10.3.3 With The Latest Supported iOS 12.5.2, But Booting With Ramiel Makes The Device Panic, Using PyBoot, It Flashes A Blue Screen Then Boots To iOS 10. Can You Please Help, I Really Want This To Work!

CPU-Apple A7
STORAGE-64GB
DEVICE-iPhone 5S
iOS 10.3.3/12.5.2

**Comment by Visualwit** [comment]
I Even Typed The Disk Number In Ramiel

**Comment by MatthewPierson** [comment]
This will not work, iOS 10.3.3's SEP is not compatible with iOS 12.5.2.

**Comment by Visualwit** [comment]
Well, Thanks! Dual Booting With iOS 11.0 Works, But It Thinks My WiFi PW Is Incorrect, WHEN IT IS!
