### ISSUE TITLE
[Bug] iPhone 7 Blob Dumping Issue.

### ISSUE THREAD

**Issue by Visualwit** [MatthewPierson/Ramiel#28]
Hi, I Have Another Issue, My Uncle Found This LOST iPhone 7 That May Be On iOS 12 Because Of The Set Wallpaper After Booting Up The Phone, I Want To Restore To That Version With SHSH Blobs But When I Use Ramiel To Dump Them, It Gives Me An Error: No APTicket Dump Found, I Do Not Know What Exact Version It Is On But I Do Not Want iOS 14!!! Please Help!!! (The iPhone IS Also Password Locked!)

**To Reproduce**

**Expected behavior**
Dump The Blobs

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Version: [e.g. 10.15.7]
 - Machine Model: [e.g. 2015 Macbook Pro]

**iOS/iPadOS Device(please complete the following information):**
 - Model: [e.g. iPhone9,1]
 - iOS Version Being Booted: [e.g. iOS 12.?]
 - Dualbooted: [e.g. N]

**Additional context**

**Comment by Visualwit** [comment]
Anyone???

**Comment by MatthewPierson** [comment]
Is the device successfully showing the dumping SHSH bootlogo or no?

**Comment by Visualwit** [comment]
It shows your user icon then goes to a black screen then on the mac, it throws me the error box

**Comment by Visualwit** [comment]
I Used Debug Mode Last Night And Got Some Python Related Exceptions, I Even Tried The SSH.TAR From One Of The Other Issues And Did Not Work, I'm Not Happy...

**Comment by Visualwit** [comment]
I Installed Mojave On My MacBook Pro, But Dumping The Blobs WORKED! However, It Dumped A Blob For iOS 14.4.2, Not 12, So, Can You Tell Me Why???

**Comment by MatthewPierson** [comment]
Whatever IPSW you use (e.g 14.4.2) is what Ramiel thinks the version of the dumped SHSH is. You can manually verify what iOS version the SHSH is for yourself if you don't already know.

**Comment by Visualwit** [comment]
OK, I'll Try My Best To Find What Version It's On By Downloading A Lot Of iOS 12 IPSWs!!!

**Comment by Visualwit** [comment]
Tried All iOS 12 IPSWs, The Wallpaper Is Also In iOS 13, Imma Try 13.

**Comment by MatthewPierson** [comment]
The IPSW you use is irrelevant, the SHSH dump will be the exact same no matter the IPSW. You just need to figure out what iOS version the device is running so that you know what version the SHSH is for

**Comment by Visualwit** [comment]
I used diagnostic mode to identify that it's on 13.1.3, but dumping the blobs keeps failing with python errors, I still need help
[Ramiel_Error_Log_8.51.AM.txt](https://github.com/MatthewPierson/Ramiel/files/6368699/Ramiel_Error_Log_8.51.AM.txt)

**Comment by Visualwit** [comment]
Just Restored To 14.6, Thanks For The Help!
