### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bkchucnc** [MatthewPierson/Ramiel#30]
ERROR: Received malformed keys
Device Information: iphone 6s ios 14.3 downgrade to 12.4.1. OS 10.15.6

Model: n71map
iOS Version: 12.4.1
Bootargs: "-v"

Other Error Information:

Expected string lengths of 64 & 32 but got 7, 7 & 7, 7
Received malformed keys

Detailed Error Log:

Key Information:

iBSS Key: Unknown
iBSS IVs: Unknown
iBEC Key: Unknown
iBEC IVs: Unknown

**Comment by Visualwit** [comment]
I Don't Think That iOS 14 SEP Is Even Compatible With iOS 12. So You May Be Stuck On 14 Forever, Sorry!

**Comment by MatthewPierson** [comment]
There's likely no firmware keys for your device, check the iPhone wiki page to make sure. Also @Visualwit is correct, iOS 14.3's SEP is not compatible with iOS 12, so even if there was keys you wouldn't be able to boot iOS 12

**Comment by bkchucnc** [comment]
Thank you.

**Comment by bkchucnc** [comment]
> I Don't Think That iOS 14 SEP Is Even Compatible With iOS 12. So You May Be Stuck On 14 Forever, Sorry! (You Cannot Downgrade..!!!)

If i use 6s, what ios version can I downgrade ?

**Comment by CiP12** [comment]
You could probably only downgrade to 14.0 at the oldest if you already have a 14.x version installed

**Comment by bkchucnc** [comment]
> You could probably only downgrade to 14.0 at the oldest if you already have a 14.x version installed

Thank you.

**Comment by LukasMFR** [comment]
I have the same issue. iPhone 6 iOS 12.4.5 Chimera and iOS 11.3 as target
