### ISSUE TITLE
[Bug] Unable to Download img4tool and img4

### ISSUE THREAD

**Issue by iMATiOS** [MatthewPierson/Ramiel#34]
My internet is working, everything else is downloaded but img4tool and img4 is not downloading. I have also tried manually placing the files in the app but doesnt work.
![Screenshot 2021-04-20 at 7 39 30 AM](https://user-images.githubusercontent.com/62501427/115329702-198c3d00-a1ac-11eb-932b-4ec23ef18779.png)
![Screenshot 2021-04-20 at 7 39 33 AM](https://user-images.githubusercontent.com/62501427/115329713-1e50f100-a1ac-11eb-8214-748fd96efe84.png)

**Comment by developerss** [comment]
just install Xcode from home brew and then try again

**Comment by therealxtrem** [comment]
Got the same problem, Homebrew changes nothing

**Comment by iMATiOS** [comment]
I just used the older version and it worked!

**Comment by therealxtrem** [comment]
Which version? Tried 1.0, 1.2 and 1.4. Neither of them worked

**Comment by developerss** [comment]
looks like you have corrupted mac and corrupted usb driver , try fix these and then try again
