### ISSUE TITLE
iPod Touch 6 (A8 64bit) DFU mode not detected

### ISSUE THREAD

**Issue by naco-siren** [MatthewPierson/Ramiel#6]
A photo worthing a thousand words...

![IMG_1236](https://user-images.githubusercontent.com/8222638/111081112-ef65a200-84be-11eb-9085-6aec90c5ed64.jpg)
(cable is connected to Mac but not visible here due to my hand)

**Comment by Visualwit** [comment]
Remember, It Needs To Be In DFU Mode! But Since This Issue Is Now Closed, You Bay Have Figured It Out! (You Did Recovery Mode In The Image...
